language: java
services:
  - docker
jdk: oraclejdk8
before_install:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG

after_script:
  - docker build -t petclic:$TRAVIS_BUILD_NUMBER .
  - docker images
